#!/sbin/sh
#setprop service.adb.root 1
if [ -e /sbin/bootrec-device ]
then
  /sbin/bootrec-device
fi

if [ -e /cache/turbo_repair.ready2copy ]
then
  rm /cache/turbo_repair.ready2copy
  mv /cache/turbo_repair.log /sdcard/turbo_repair.log
fi

if [ -e /cache/recovery/boot -o -s /dev/keycheck ]
then
  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /mnt/sdcard
  umount -l /sdcard
  rm -r /sdcard
  rm -r /mnt/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  #umount -l /cache
  mount /dev/block/mmcblk0p1 /sdcard
  chmod 755 /res/aromapreinstall/aroma-installer
  chmod 755 /res/aromapreinstall/*.sh
  /res/aromapreinstall/aroma-installer 1 0 "/res/aromapreinstall/aroma-installer-res.zip"
  #touch /tmp/bootrec
  if [ ! -e /tmp/bootrec ]
  then
    reboot
  fi
fi

if [ -e /tmp/bootrec ]
then
  rm /cache/recovery/boot
  rm /tmp/bootrec
  umount -l /cache
  mount /dev/block/mmcblk0p1 /sdcard
  /sbin/adbd&/sbin/recovery
fi
    
# Couldn't be bothered doing this in init syntax (I'm ignorant) so we'll link dalvik here instead
mkdir /data/dalvik-cache
    chown system:system /data/dalvik-cache
    chmod 0771 /data/dalvik-cache
mkdir /cache/dalvik-cache
mount -o bind /data/dalvik-cache /cache/dalvik-cache
    chown system:system /cache/dalvik-cache
    chmod 0771 /cache/dalvik-cache

# JB/ICS detection
/sbin/ics-or-jb
    
#continue booting



