#!/sbin/busybox sh

BOOTREC_CACHE_NODE="/dev/block/mtdblock2 b 31 2"
BOOTREC_CACHE="/dev/block/mtdblock2"
BOOTREC_EVENT_NODE="/dev/input/event1 c 13 65"
BOOTREC_EVENT="/dev/input/event1"
BOOTREC_LED_RED="/sys/class/leds/red/brightness"
BOOTREC_LED_GREEN="/sys/class/leds/green/brightness"
BOOTREC_LED_BLUE="/sys/class/leds/blue/brightness"
BOOTREC_VIBRATOR="/sys/class/timed_output/vibrator/enable"

