#!/sbin/busybox sh

# start aroma bootmenu
source /sbin/bootrec-device
busybox mount -t yaffs2 $BOOTREC_CACHE /cache
busybox mkdir /sdcard
busybox mount /dev/block/mmcblk0p1 /sdcard
busybox mkdir /turbo
busybox mount -o bind /sdcard/turbo /turbo
/sbin/aroma 1 0 "/sbin/aroma-res.zip"
# copy repair log to sdcard if requested
if [ -e /tmp/turbo_repair.ready2copy ]; then
    busybox rm /tmp/turbo_repair.ready2copy
    busybox mv /tmp/turbo_repair.log /sdcard/turbo_repair.log
fi
busybox sync
busybox umount -l /dev/block/mmcblk0p1
reboot
